[build]
  publish = "."

# Redirects para subdomínios específicos (HTTP e HTTPS)
[[redirects]]
  from = "https://admin.pontofacil.app.br/*"
  to = "/admin.html"
  status = 200
  force = true

[[redirects]]
  from = "http://admin.pontofacil.app.br/*"
  to = "/admin.html"
  status = 200
  force = true

[[redirects]]
  from = "https://app.pontofacil.app.br/*"
  to = "/empresa.html"
  status = 200
  force = true

[[redirects]]
  from = "http://app.pontofacil.app.br/*"
  to = "/empresa.html"
  status = 200
  force = true

[[redirects]]
  from = "https://ponto.pontofacil.app.br/*"
  to = "/ponto.html"
  status = 200
  force = true

[[redirects]]
  from = "http://ponto.pontofacil.app.br/*"
  to = "/ponto.html"
  status = 200
  force = true

# Redirects para domínio principal (HTTP e HTTPS)
[[redirects]]
  from = "https://www.pontofacil.app.br/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "http://www.pontofacil.app.br/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "https://pontofacil.app.br/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "http://pontofacil.app.br/*"
  to = "/index.html"
  status = 200
  force = true

# Fallback para URLs diretas no domínio Netlify
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/empresa"
  to = "/empresa.html"
  status = 200

[[redirects]]
  from = "/ponto"
  to = "/ponto.html"
  status = 200

# Headers para permitir geolocalização
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "geolocation=(self)"
    Feature-Policy = "geolocation 'self'"

# SPA fallback (deve ser o último)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
