[build]
  publish = "."

# Redirects para subdomínios específicos
[[redirects]]
  from = "https://admin.pontofacil.app.br/*"
  to = "/admin.html"
  status = 200
  force = true

[[redirects]]
  from = "https://app.pontofacil.app.br/*"
  to = "/empresa.html"
  status = 200
  force = true

[[redirects]]
  from = "https://ponto.pontofacil.app.br/*"
  to = "/ponto.html"
  status = 200
  force = true

# Redirects para domínio principal
[[redirects]]
  from = "https://www.pontofacil.app.br/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "https://pontofacil.app.br/*"
  to = "/index.html"
  status = 200
  force = true

# Fallback para URLs diretas no domínio Netlify
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/empresa"
  to = "/empresa.html"
  status = 200

[[redirects]]
  from = "/ponto"
  to = "/ponto.html"
  status = 200

# SPA fallback (deve ser o último)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
